name: Deploy to Production

on:
  push:
    tags:
      - "[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]"

jobs:

  build:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2, with: {fetch-depth: 0}}
      - {name: Initialize dependencies, uses: ./.github/actions/init-deps}
      - {name: Build docs, run: make docs, env: {SPHINX_HTML_BASEURL: "https://robpol86.com/"}}
      - {name: Store HTML, uses: actions/upload-artifact@v2, with: {name: html, path: build/html/, if-no-files-found: error}}

  publish:
    name: Publish to NFSN
    runs-on: ubuntu-latest
    needs: build
    concurrency: "publish-${{ github.event_name }}"
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: build/html/}}
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          source: build/html/
          user: robpol86_robpol86
          ssh-key: "${{ secrets.NFSN_SSH_KEY }}"
          cf-token: "${{ secrets.TOKEN_CF_PURGE_CACHE }}"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - {name: Check out repository code, uses: actions/checkout@v2}
      - {name: Fetch HTML files, uses: actions/download-artifact@v2, with: {name: html, path: build/html/}}
      - {name: Archive HTML files, run: tar -C build -czvf html.tar.gz html/}
      - name: Determine title and body
        id: data
        run: |
          grep -A5 "^## ${{ github.ref_name }}$" CHANGELOG.md
